language: python
python:
    - "3.6.3"
# Install all dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls

services:
    - postgresql
# command to create database
before_script:
    - psql -c 'create database flask_api;' -U postgres
    - python manage.py db init
    - python manage.py db migrate
    - python manage.py db upgrade
# command to run tests
script:
    - py.test --cov=recipe tests/
after_success:
    - coveralls