FORMAT: 1A
HOST: https://yummy-recipev2.herokuapp.com/

# Yummy Recipes
## Group Authentication

## Registration [/auth/register]

### Register a User  [POST]

It takes a JSON object containing a username, email and password.

Password cannot be less that  characters.

Username must be Unique.


+ Request (application/json)

        {
            "username": "Bruno",
            "email" : "silverjimmy2@gmail.com",
            "password": "12345678923"

        }

+ Response 201 (application/json)

    + Headers

            Content-Type:application/json

    + Body

        {
            "message": "User Registration success!"
        }

## Login [/auth/login]

### Authenitcate and Authorize a user [POST]

Use your correct email and password.
Note the token returned on successful login. It is required to access other
resources.

+ Request (application/json)

        {
            "username": "Bruno",
            "password": "12345678923"

        }

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

        {
                "status": "success",
                "message": "You have successfully logged in.",
                "auth_token": "Your_Token_Here"
        }

### Group Category

## Category endpoints [/category/]

### Create a new category  [POST]

It takes a JSON object containing a name and description.

Category name must be Unique.


+ Request (application/json)

    + Headers

            Content-Type:application/json
    + body
        {
          "name": "Matooke",
          "description": "mashed"
        }

+ Response 201 (application/json)

    + Headers

            Authorization : "Your_token_here"

    + Body

    {
        "message": "Category Matooke Added!",
        "status": "success"
    }

+ Response 409 (application/json)


    + Body

        {
            "message": "This Category already exists !",
            "status": "fail"
        }

+ Response 400 (application/json)


    + Body

    {
        "message": "Please enter a Category name!",
        "status": "fail"
    }



## Retrieve all categories  [GET]

This endpoint returns all categories owned by the authenitcated user

It takes in no arguments except the token.


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"



+ Response 401

    + Headers

            Content-Type:application/json
            
## Single Category Resource [/category/4]

### Get a single category [GET]

This endpoint returns details of a category owned by the authenitcated user


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"



+ Response 401

    + Headers

            Content-Type:application/json


    + Body


    {
    "status": "fail",
    "message": "Invalid token. Please log in again."
    }

+ Response 200

    + Headers

            Content-Type:application/json

    + Body


    {
        "id": 4,
        "title": "SouthAfrica",
        "description": "bruno@gmail.com",
        "created_on": "2017-08-07 11:24:07.440470",
        "recipes": []   
    }


### Update a single category [PUT]

This endpoint Updates details of a category owned by the authenitcated user


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"

    + body
        {
          "name": "Matooke",
          "description": "boiled..."
        }

+ Response 401

    + Headers

            Content-Type:application/json


    + Body


    {
    "status": "fail",
    "message": "Invalid token. Please log in again."
    }

+ Response 200

    + Headers

            Content-Type:application/json

    + Body


    {
        "id": 4,
        "title": "Matooke",
        "description": "boiled...",
        "created_on": "2017-08-07 11:24:07.440470",
        "recipes": []   
    }
    
### Delete a single category [DELETE]

This endpoint Deletes details of a category owned by the authenitcated user


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"

+ Response 401

    + Headers

            Content-Type:application/json


    + Body


    {
        "status": "fail",
        "message": "Invalid token. Please log in again."
    }

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

    {
        'message': 'Category deleted.!!',
        'status': 'success'
    }

## Category Recipe Resource [/category/4/recipes/]

### Create a Category Recipe [POST]

It takes a JSON object containing a name and description.

Category Recipe name must be Unique to the category.


+ Request (application/json)

    + Headers

            Content-Type:application/json
    + body
        {
          "name": "Ugali",
          "description": "boiled with water at room temp."
        }

+ Response 201 (application/json)

    + Headers

            Authorization : "Your_token_here"

    + Body

    {
        "message": "Category Recipe Ugali Added!",
        "status": "success"
    }

+ Response 409 (application/json)


    + Body

        {
            "message": "This Category Recipe already exists !",
            "status": "fail"
        }

+ Response 400 (application/json)


    + Body

    {
        "message": "Please enter Recipe name!",
        "status": "fail"
    }
### Retrieve a category Recipes [GET]

This endpoint Returns  a list  category owned by the authenitcated user


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"

+ Response 401

    + Headers

            Content-Type:application/json


+ Response 200

    + Headers

            Content-Type:application/json

    + Body

    {
        "id": <id>,
        "title": "string here",
        "description": "string here",
        "created_on": "2017-08-07 19:54:49.656095"
    }


### Update a Category Recipe [PUT]

It takes a JSON object containing a name and description.

Category Recipe name must be Unique to the category.


+ Request (application/json)

    + Headers

            Content-Type:application/json
    + body
        {
          "name": "Posho",
          "description": "Boiled withw water"
        }

+ Response 201 (application/json)

    + Headers

            Authorization : "Your_token_here"

    + Body

    {
        "message": "Category Recipe Posho Updated!",
        "status": "success"
    }

+ Response 409 (application/json)


    + Body

        {
            "message": "This Category Recipe already exists !",
            "status": "fail"
        }

+ Response 400 (application/json)


    + Body

    {
        "message": "Please enter Recipe name!",
        "status": "fail"
    }
    
+ Response 404 (application/json)

    + Body
        {
            'message': 'Category does not exist!!',
            'status': 'fail'
        }

### Delete a single category Recipe [DELETE]

This endpoint Deletes details of a category Recipe owned by the authenitcated user


+ Request (application/json)

      + Headers

              Authorization : "Your_token_here"

+ Response 401

    + Headers

            Content-Type:application/json


    + Body


    {
        "status": "fail",
        "message": "Invalid token. Please log in again."
    }

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

    {
        'message': 'Category Recipe deleted.!!',
        'status': 'success'
    }